<a href="https://colab.research.google.com/github/Vaish-922/WebAppWithAI/blob/main/MovieReccomendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [131]:
import numpy as np
import tensorflow as tf


1. Harry Potter
2. Interstellar
3. Breakfast at Tiffany's
4. The Martian
5. La La Land
6. The Shawshank redemption
7. Jaws
8. Pride and Prejudice
9. Iron Man
10. Pretty Woman

1. Science Fiction
2. Romance
3. Action
4. Classic
5. Adventure
6. Mystery

In [132]:


user_count=6
movie_count=7
movie_name=['Harry Potter',
'Interstellar',
'Breakfast at Tiffanys',
'The Martian',
'La La Land',
'The Shawshank redemption',
'Jaws',
'Pride and Prejudice',
'Iron Man',
'Pretty Woman']

users=tf.Variable(np.random.rand(user_count,6),dtype = tf.float64)
movies=tf.Variable(np.array([ [8,2,9,1,7,5], 
                              [10,1,6,1,8,2], 
                              [1,8,2,9,2,1], 
                              [10,4,9,7,10,9], 
                              [1,10,2,5,1,2],
                              [7,2,9,3,10,9], 
                              [7,2,10,2,9,7], 
                              [1,10,2,10,1,2], 
                              [7,4,10,1,6,3], 
                              [1,10,2,4,1,2] ])/10, dtype = tf.float64)

ratings = np.array([
[8, 9, 7, 2, 8, 4, 7, 1, 6, 8],
[5,10,0,9,0,1,8,0,2,0],
[0,8,4,10,7,9,0,6,5,8],
[0,9,0,7,2,10,0,0,6,0],
[6,3,0,1,9,10,7,9,8,5],
[8,10,0,9,5,10,8,0,8,0]
])



In [133]:
38

user_count+=1;
new_rate=[0,1,2,3,4,5,6,7,8,9]

#getting ratings of new user
print("Enter the ratings of the following movies: \n")
# for i in range(10):
#   temp=float(input(movie_name[i]+': '))
#   new_rate.append(temp)

ratings=np.append(ratings,[new_rate],axis=0)

#adding user row to user matrix
new_user = np.random.rand(1,6)
users=np.append(users,new_user,axis=0)






Enter the ratings of the following movies: 



In [134]:

users = tf.Variable(users)
mask = np.ma.masked_not_equal(ratings, 0).mask

ratings = tf.constant(ratings, dtype=tf.float64)

optimizer = tf.optimizers.Adam()

In [135]:
training_value = [users, movies]

for step in range(5000):

    with tf.GradientTape() as tape:

        final = tf.matmul(users, movies, transpose_b=True)
        final = tf.sigmoid(final)*10
        final = final*mask

        

        loss = tf.losses.mean_squared_error(ratings, final)
        
        
        gradients = tape.gradient(loss, training_value)
        optimizer.apply_gradients(zip(gradients, training_value))




In [136]:
final = tf.matmul(users, movies, transpose_b=True)
#final = tf.nn.relu(final)
final=tf.sigmoid(final)*10

final = np.rint(final.numpy())

print(final)

[[ 8.  9.  7.  2.  8.  4.  7.  1.  6.  8.]
 [ 5. 10.  9.  9.  6.  1.  8.  5.  2.  1.]
 [ 7.  8.  4. 10.  7.  9.  7.  6.  5.  8.]
 [ 6.  9.  5.  7.  2. 10.  3.  6.  6.  1.]
 [ 6.  3.  6.  1.  9. 10.  7.  9.  8.  5.]
 [ 8. 10.  6.  9.  5. 10.  8.  6.  8.  5.]
 [ 5.  1.  2.  3.  4.  5.  6.  7.  8.  9.]]
